version: '3.3'
services:
  rabbit:
    hostname: rabbit
    restart: always
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "${RABBITMQ_MGT_PORT}:15672"
      - "${RABBITMQ_PORT}:5672"
    volumes:
      - /tmp/distributed-scraper/rabbitmq:/var/lib/rabbitmq
  redis:
    hostname: redis
    restart: always
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "${REDIS_PORT}:6379"
  worker:
    restart: always
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./worker:/worker
    depends_on:
      - rabbit
      - redis
    environment:
      CELERY_BROKER_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbit:${RABBITMQ_PORT}
      CELERY_RESULT_BACKEND: redis://:${REDIS_PASS}@redis:${REDIS_PORT}/0
      MONGO_URI: ${MONGO_URI}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
  monitor:
    hostname: monitor
    image: mher/flower:latest
    depends_on:
      - rabbit
      - redis
    ports:
      - "${FLOWER_PORT}:5555"
    environment:
      CELERY_BROKER_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbit:${RABBITMQ_PORT}
      CELERY_RESULT_BACKEND: redis://:${REDIS_PASS}@redis:${REDIS_PORT}/0
      DATADOG_HOST: datadog
  rproxy:
    hostname: rproxy
    image: mattes/rotating-proxy:latest
    environment:
      tors: "25"
    ports:
      - "5566:5566"
      - "4444:4444"
  datadog:
    hostname: datadog
    build: datadog
    depends_on:
      - rabbit
      - worker
      - redis
    environment:
      DD_API_KEY: ${DATADOG_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
